#baseURL = "https://calumjackson.github.io/techblog/"
baseURL = "https://www.calumjackson.co.uk"

languageCode = "en-us"
title = "Tech Blog"
publishDir = "../build"
theme = "hugo-theme-learn"
canonifyURLs = "true"
enableEmoji = "true"
favicon = "images/site_images/campfire.png"
disqusShortname = "cjtechdiscuss"


[params]
  themeVariant = "cj"

[deployment]
name = "gcs-deployment"

[[deployment.targets]]
# An arbitrary name for this target.
name = "cj-deployment"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
URL = "gs://cj-hugo-test-site"
